version: "3"
services:
  php72_service:
    image: romeoz/docker-nginx-php:7.1
    container_name: web72
    volumes:
      - "./source:/var/www/source"
      - "./nginx/:/etc/nginx/sites-enabled/"
    links:
      - mysql:mysql_57
    network_mode: bridge
    restart: always
    working_dir: /var/www/source
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    container_name: mysql_57 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    network_mode: bridge
    restart: always